<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'App\\Server\\' => array($baseDir . '/src/server'),
    'App\\' => array($baseDir . '/src/app'),
);
