<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4b3e35ed09ea5fe35d49ba2f05a3b39d
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\Server\\' => 11,
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\Server\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/server',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/app',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4b3e35ed09ea5fe35d49ba2f05a3b39d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4b3e35ed09ea5fe35d49ba2f05a3b39d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
